#!/usr/bin/env bash

this_dir="$(dirname "$(readlink -f "$0")")"
# shellcheck source=helpers.sh
source "${this_dir}/helpers.sh"

# From <https://docs.brew.sh/Homebrew-on-Linux>
setup_homebrew() {
  sudo apt-get install build-essential curl file git gcc

  git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
  mkdir -p ~/.linuxbrew/bin
  ln -sf ../Homebrew/bin/brew ~/.linuxbrew/bin
  eval "$(~/.linuxbrew/bin/brew shellenv)"

  brew install core
}

install_gems() {
  # From <https://github.com/jethrodaniel/.git-hooks>
  gem install overcommit \
    && overcommit --install \
    && git clone https://github.com/jethrodaniel/.git-hooks \
    && cp .git-hooks/.overcommit.yml.example .overcommit.yml \
    && overcommit --sign \
    && overcommit --sign prepare-commit-msg \
    && overcommit --sign commit-msg

  gem install ripper-tags
  gem install gem-ripper-tags
  gem ripper_tags

  gem install gem-browse
}

install_dotfiles() {
  if [ "$verbose" == 'true' ]; then
    echo "VERBOSE"
  fi

  git clone --recurse-submodules https://github.com/jethrodaniel/dotfiles "$HOME/dotfiles/"

  [ "$verbose" == 'true' ] && echo "Updating \`apt\` ..."
  sudo apt-get update

  [ "$verbose" == 'true' ] && echo "Setting up Homebrew ..."
  setup_homebrew

  [ "$verbose" == 'true' ] && echo "Running \`brew bundle\`..."
  brew bundle

  [[ "${PWD##*/}" == 'dotfiles' ]] && pushd dotfiles
  [ "$verbose" == 'true' ] && echo "Installing dotfiles with \`stow\` ..."
  if stow --target="$HOME" ./home; then
    echo 'Installed symlinks ...'
  else
    echo '`stow` failed. You probably need to delete existing files.'
    [ "$CI" = 'true' ] && ./stow.rb
    exit 1
  fi
  popd

  [ "$verbose" == 'true' ] && echo "Installing misc packages from \`apt\`..."
  sudo apt-get install -y \
    x11-xkb-utils \
    i3 \
    pavucontrol \
    ttf-ancient-fonts

  [ "$verbose" == 'true' ] && echo "Installing some ruby gems ..."
  install_gems

  [ "$verbose" == 'true' ] && echo "Linking tmux config ..."
  # Symlink tmux settings into the home dir
  ln -fs ~/.tmux/conf ~/.tmux.conf

  say <<-MSG
		Done. Be sure to run

			\`prefix+I\` inside tmux, then reopen tmux.
	MSG
}

PROGNAME=$0

usage() {
  cat <<-EOF
		Usage: $PROGNAME [-v] [-y] [install]

		Commands
		  install    Installs these dotfiles
		  <blank>    With no options, shows usage

		Options
		  -y    Reply \`y\` to any prompts
		  -v    Be verbose

	EOF
}

main() {
  # Parse options
  while getopts ':vy' o; do
    case $o in
      v) verbose=true
        ;;
      y) force_yes=true
        ;;
      *)
    esac
  done
  shift $((OPTIND-1))

  if [ "$1" != 'install' ]; then
    usage
    exit
  fi

  say <<-MSG
		Setting up dotfiles...

		This is probably going to take a while. Time for ☕.
	MSG

  confirmation=`cat <<-MSG

		Sure you want to install? It's gonna be like an hour or more.

		And will currently just try to overwrite everything.

    💣
	MSG`

  if [ "$force_yes" = 'true' ] || $(ask "$confirmation"); then
    echo 'Installing the dotfiles...'
    install_dotfiles
  else
    echo 'Exiting...'
  fi
}

main "$@" &

main_pid=$!
install_script_name=$(ps -p $main_pid -o comm=)

i=1
while ps -p $main_pid &>/dev/null; do
  sleep $((60 * 9))
  echo "($main_pid) $install_script_name is still running ($((9 * i)) min) ..."
  i=$((i + 1))
done
echo "$install_script_name has finished!"

wait $main_pid
