#!/usr/bin/env bash

this_dir=$(dirname $(readlink -f $0))
source "${this_dir}/helpers.sh"

say "Setting up dotfiles..."

set -x

#------------------------------------------------------------
# Prerequisite software
#------------------------------------------------------------
sudo apt-get update

sudo apt-get install -y vim \
                        vim-gnome \
                        git \
                        tree \
                        tmux \
                        xclip \
                        trash-cli \
                        x11-xkb-utils

sudo apt-get -y upgrade \
  && sudo apt-get -y autoremove

#------------------------------------------------------------
# Homeshick
#------------------------------------------------------------
git clone https://github.com/andsens/homeshick.git \
          $HOME/.homesick/repos/homeshick
source "$HOME/.homesick/repos/homeshick/homeshick.sh"

set +x
if ask 'Clone with ssh?'; then
  set -x
  yes | homeshick clone git@github.com:jethrodaniel/dotfiles
else
  set -x
  yes | homeshick clone jethrodaniel/dotfiles
fi

#------------------------------------------------------------
# Rbenv
#------------------------------------------------------------
~/.rbenv/bin/rbenv init

git clone https://github.com/rbenv/ruby-build.git \
          ~/.rbenv/plugins/ruby-build

#------------------------------------------------------------
# Get public GPG keys from Github
#------------------------------------------------------------
~/.homesick/repos/dotfiles/gpg.rb

set +x

say "Done. Be sure to run"
say "\t${reset}run 'ctrl+f+I' inside tmux"
say "to get started."
