#!/usr/bin/env bash

this_dir=$(dirname $(readlink -f $0))
source "${this_dir}/helpers.sh"

say "Setting up dotfiles..."

set -x

#------------------------------------------------------------
# Prerequisite software
#------------------------------------------------------------
sudo apt-get update

sudo apt-get install -y vim \
                        vim-gnome \
                        git \
                        tree \
                        tmux \
                        xclip \
                        trash-cli \
                        x11-xkb-utils

#------------------------------------------------------------
# Homeshick
#------------------------------------------------------------
git clone https://github.com/andsens/homeshick.git \
          $HOME/.homesick/repos/homeshick
source "$HOME/.homesick/repos/homeshick/homeshick.sh"

set +x
if ask 'Clone with ssh?'; then
  set -x
  yes | homeshick clone git@github.com:jethrodaniel/dotfiles
else
  set -x
  yes | homeshick clone jethrodaniel/dotfiles
fi

#------------------------------------------------------------
# Rbenv plugins
#------------------------------------------------------------
git clone https://github.com/rbenv/ruby-build.git \
          ~/.rbenv/plugins/ruby-build

#------------------------------------------------------------
# hub
#------------------------------------------------------------
set +x
if ask 'Install hub?'; then
  set -x
  temp_dir=$(mktemp -d)
  cd $temp_dir
  wget https://github.com/github/hub/releases/download/v2.6.1/hub-linux-amd64-2.6.1.tgz
  tar xvzf hub-linux-amd64-2.6.1.tgz
  mv "$temp_dir/hub-linux-amd64-2.6.1/bin/hub" ~/bin
  cd -
  rm -rf $temp_dir
else
  set -x
fi

source .profile

set +x

say "Done. Be sure to run"
echo -e "\trun \`ctrl+f+I\` inside tmux"
echo 'then'
echo -e "\trbenv install 2.5.3"
echo -e "\trbenv global 2.5.3"
echo -e "\t~/bin/gpg.rb"
say "to get started."
