# rubocop styles

AllCops:
  EnabledByDefault: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  UseHashRocketsWithSymbolValues: true
  PreferHashRocketsForNonAlnumEndingSymbols: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

