# rubocop styles

AllCops:
  TargetRubyVersion: 2.4

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  UseHashRocketsWithSymbolValues: true
  PreferHashRocketsForNonAlnumEndingSymbols: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/IndentHeredoc:
  EnforcedStyle: squiggly

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'

Metrics/LineLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'

Style/CommentedKeyword:
  Enabled: false
