# rubocop styles

AllCops:
  TargetRubyVersion: 2.4

# Hash rockets for everything
Style/HashSyntax:
  EnforcedStyle: hash_rockets
  UseHashRocketsWithSymbolValues: true
  PreferHashRocketsForNonAlnumEndingSymbols: true

# {:foo => :bar} instead of  { :foo => :bar }
# {} is for hashes
# { } is for blocks
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Always use <<~HERE
# HERE
Layout/IndentHeredoc:
  EnforcedStyle: squiggly

# Rake tasks usually end up having no respect for line lengths.
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
Metrics/LineLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'

# Rspec.describe Samsquanch do
#   ...
# end # describe Samsquanch
Style/CommentedKeyword:
  Enabled: false

# Default method length of 10 lines is a bit low
Metrics/MethodLength:
  Max: 30

Style/RescueStandardError:
  Enabled: false

# xml = Nokogiri::XML(File.open file) do |config|
#   ...
# end
NestedParenthesizedCalls:
  Enabled: false
