---

# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

AllCops:
  # Show full messages
  ExtraDetails: true

# Spec DSL creates large blocks, especially when nesting
#
# And gemspecs are usually pretty long
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - '**/*.gemspec'

# Why can't we use pretty unicode?
Style/AsciiComments:
  Enabled: false

# `while line = gets` is idiomatic
Lint/AssignmentInCondition:
  Enabled: false

# just shuddap
Gemspec/RequiredRubyVersion:
  Enabled: false

# 6 is a bit restrictive
Metrics/CyclomaticComplexity:
  Max: 8

# Only use the stabby lambda. f = -> x { }
Style/Lambda:
  EnforcedStyle: literal

# f -> x { x + 1 }
Style/StabbyLambdaParentheses:
  EnforcedStyle: require_no_parentheses

# super.match? /simple/
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# Usually leads to unneccesary comments
Style/Documentation:
  Enabled: false

# {} for hashes, { } for blocks
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Hash rockets for everything
Style/HashSyntax:
  EnforcedStyle: hash_rockets
  UseHashRocketsWithSymbolValues: true
  PreferHashRocketsForNonAlnumEndingSymbols: true

# def a, b
#   ...
# end
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

# Always use <<~HERE
# HERE
Layout/HeredocIndentation:
  EnforcedStyle: squiggly

# Default method length of 10 lines is a bit low
Metrics/MethodLength:
  Max: 30

# `rescue` is provided for a reason
Style/RescueStandardError:
  Enabled: false

# -> (a) { } is good
# ->(a) { } is just as ugly as if( true )
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Default of 15 is a bit low
Metrics/AbcSize:
  Max: 20

# match? *TYPES
Lint/AmbiguousOperator:
  Enabled: false
