# frozen_string_literal: true

ruby '2.3.1'

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rspec', '~> 3.8'      # Testing
gem 'pry-byebug', '~> 3.7' # Debugging
