#!/usr/bin/env ruby

require 'erb'

message_file = ARGV[0]

branch = %x[git rev-parse --abbrev-ref HEAD]&.strip

issue = branch.match(/\d+/)&.captures&.flatten

commit_template = File.read message_file

commit_message = ERB.new(commit_template).result.gsub '[#]', ''

File.write message_file, commit_message
